/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Leaf_gold.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Leaf_gold.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['uploads-files-4395313-1'].geometry} material={nodes['uploads-files-4395313-1'].material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/Leaf_gold.gltf')
