/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/Traditional.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../Contexts/Customization";
import { MeshStandardMaterial } from "three";
// import { HexColorPicker } from 'react-colorful'

export function Traditional_ring(props) {
  // const diamondMaterial = materials.Material_2
  // const [color, setColor] = useState('white')
  const { material } = useCustomization();
  const { nodes, materials } = useGLTF("./models/Traditional.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.018, 0.001]}>
        <group position={[0, -0.018, -0.001]} scale={11.4}>
          <group rotation={[1.571, 0, 0]} scale={0.01}>
            {/* materials.metal is the metal part of the ring
            Material_1 consists of shadows
            Material_2 makes up the stones of the ring
            Material_3 is the main stone of the ring  */}

            {/* circular metal part of the ring */}
            <mesh
              geometry={nodes.alliance.geometry}
              material={materials.metal}
              position={[0, -2.205, -0.086]}
              scale={0.18}
            />

            <mesh
              geometry={nodes.dia001.geometry}
              material={materials.Material_2}
              position={[0, 7.905, -0.087]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia002.geometry}
              material={materials.Material_2}
              position={[1.439, 7.802, -0.087]}
              rotation={[0, 0, -0.143]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia003.geometry}
              material={materials.Material_2}
              position={[2.849, 7.496, -0.087]}
              rotation={[0, 0, -0.286]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia004.geometry}
              material={materials.Material_2}
              position={[4.2, 6.992, -0.087]}
              rotation={[0, 0, -0.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia005.geometry}
              material={materials.Material_2}
              position={[5.466, 6.3, -0.087]}
              rotation={[0, 0, -0.571]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia006.geometry}
              material={materials.Material_2}
              position={[6.621, 5.436, -0.087]}
              rotation={[0, 0, -0.714]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia007.geometry}
              material={materials.Material_2}
              position={[7.641, 4.416, -0.087]}
              rotation={[0, 0, -0.857]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia008.geometry}
              material={materials.Material_2}
              position={[8.506, 3.261, -0.087]}
              rotation={[0, 0, -1]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia009.geometry}
              material={materials.Material_2}
              position={[9.197, 1.995, -0.087]}
              rotation={[0, 0, -1.142]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia010.geometry}
              material={materials.Material_2}
              position={[9.701, 0.643, -0.087]}
              rotation={[0, 0, -1.285]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia011.geometry}
              material={materials.Material_2}
              position={[10.008, -0.766, -0.087]}
              rotation={[0, 0, -1.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia012.geometry}
              material={materials.Material_2}
              position={[10.111, -2.205, -0.087]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia013.geometry}
              material={materials.Material_2}
              position={[10.008, -3.644, -0.087]}
              rotation={[0, 0, -1.714]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia014.geometry}
              material={materials.Material_2}
              position={[9.701, -5.054, -0.087]}
              rotation={[0, 0, -1.856]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia015.geometry}
              material={materials.Material_2}
              position={[9.197, -6.405, -0.087]}
              rotation={[0, 0, -1.999]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia016.geometry}
              material={materials.Material_2}
              position={[8.505, -7.671, -0.087]}
              rotation={[0, 0, -2.142]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia017.geometry}
              material={materials.Material_2}
              position={[7.641, -8.826, -0.087]}
              rotation={[0, 0, -2.285]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia018.geometry}
              material={materials.Material_2}
              position={[6.621, -9.846, -0.087]}
              rotation={[0, 0, -2.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia019.geometry}
              material={materials.Material_2}
              position={[5.466, -10.711, -0.087]}
              rotation={[0, 0, -2.57]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia020.geometry}
              material={materials.Material_2}
              position={[4.2, -11.402, -0.087]}
              rotation={[0, 0, -2.713]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia021.geometry}
              material={materials.Material_2}
              position={[2.848, -11.906, -0.087]}
              rotation={[0, 0, -2.856]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia022.geometry}
              material={materials.Material_2}
              position={[1.439, -12.213, -0.087]}
              rotation={[0, 0, -2.999]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia023.geometry}
              material={materials.Material_2}
              position={[0, -12.316, -0.087]}
              rotation={[0, 0, Math.PI]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia024.geometry}
              material={materials.Material_2}
              position={[-1.439, -12.213, -0.087]}
              rotation={[0, 0, 2.999]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia025.geometry}
              material={materials.Material_2}
              position={[-2.849, -11.906, -0.087]}
              rotation={[0, 0, 2.856]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia026.geometry}
              material={materials.Material_2}
              position={[-4.2, -11.402, -0.087]}
              rotation={[0, 0, 2.713]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia027.geometry}
              material={materials.Material_2}
              position={[-5.466, -10.711, -0.087]}
              rotation={[0, 0, 2.57]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia028.geometry}
              material={materials.Material_2}
              position={[-6.621, -9.846, -0.087]}
              rotation={[0, 0, 2.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia029.geometry}
              material={materials.Material_2}
              position={[-7.641, -8.826, -0.087]}
              rotation={[0, 0, 2.285]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia030.geometry}
              material={materials.Material_2}
              position={[-8.506, -7.671, -0.087]}
              rotation={[0, 0, 2.142]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia031.geometry}
              material={materials.Material_2}
              position={[-9.197, -6.405, -0.087]}
              rotation={[0, 0, 1.999]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia032.geometry}
              material={materials.Material_2}
              position={[-9.701, -5.054, -0.087]}
              rotation={[0, 0, 1.856]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia033.geometry}
              material={materials.Material_2}
              position={[-10.008, -3.644, -0.087]}
              rotation={[0, 0, 1.714]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia034.geometry}
              material={materials.Material_2}
              position={[-10.111, -2.205, -0.087]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia035.geometry}
              material={materials.Material_2}
              position={[-10.008, -0.766, -0.087]}
              rotation={[0, 0, 1.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia036.geometry}
              material={materials.Material_2}
              position={[-9.701, 0.643, -0.087]}
              rotation={[0, 0, 1.285]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia037.geometry}
              material={materials.Material_2}
              position={[-9.197, 1.995, -0.087]}
              rotation={[0, 0, 1.142]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia038.geometry}
              material={materials.Material_2}
              position={[-8.505, 3.261, -0.087]}
              rotation={[0, 0, 1]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia039.geometry}
              material={materials.Material_2}
              position={[-7.641, 4.416, -0.087]}
              rotation={[0, 0, 0.857]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia040.geometry}
              material={materials.Material_2}
              position={[-6.621, 5.436, -0.087]}
              rotation={[0, 0, 0.714]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia041.geometry}
              material={materials.Material_2}
              position={[-5.466, 6.3, -0.087]}
              rotation={[0, 0, 0.571]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia042.geometry}
              material={materials.Material_2}
              position={[-4.2, 6.992, -0.087]}
              rotation={[0, 0, 0.428]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia043.geometry}
              material={materials.Material_2}
              position={[-2.848, 7.496, -0.087]}
              rotation={[0, 0, 0.286]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.dia044.geometry}
              material={materials.Material_2}
              position={[-1.439, 7.802, -0.087]}
              rotation={[0, 0, 0.143]}
              scale={[0.006, 0.007, 0.006]}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_001.geometry}
              material={materials.Material_1}
              position={[-0.342, 10.309, 4.141]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_002.geometry}
              material={materials.Material_1}
              position={[1.256, 10.309, 3.786]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_003.geometry}
              material={materials.Material_1}
              position={[2.801, 10.309, 3.124]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_004.geometry}
              material={materials.Material_1}
              position={[3.53, 10.309, 1.639]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_005.geometry}
              material={materials.Material_1}
              position={[3.769, 10.309, -0.023]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_006.geometry}
              material={materials.Material_1}
              position={[3.547, 10.309, -1.695]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_007.geometry}
              material={materials.Material_1}
              position={[2.862, 10.309, -3.16]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_008.geometry}
              material={materials.Material_1}
              position={[1.361, 10.309, -3.905]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_009.geometry}
              material={materials.Material_1}
              position={[-0.266, 10.309, -4.141]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_010.geometry}
              material={materials.Material_1}
              position={[-1.9, 10.309, -3.935]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_011.geometry}
              material={materials.Material_1}
              position={[-3.436, 10.309, -3.205]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_012.geometry}
              material={materials.Material_1}
              position={[-4.165, 10.309, -1.693]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_013.geometry}
              material={materials.Material_1}
              position={[-4.359, 10.309, -0.066]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_014.geometry}
              material={materials.Material_1}
              position={[-4.161, 10.309, 1.569]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_015.geometry}
              material={materials.Material_1}
              position={[-3.44, 10.309, 3.052]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            <mesh
              geometry={nodes.diamond_side_cuchion_016.geometry}
              material={materials.Material_1}
              position={[-1.983, 10.309, 3.763]}
              rotation={[Math.PI, -1.466, Math.PI]}
              scale={0.007}
            />
            {/* metal encasing the main stone of the ring */}
            <mesh
              geometry={nodes.entourage.geometry}
              material={materials.metal}
              position={[-0.3, -1.307, 19.923]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Object.geometry}
              material={materials.Material_3}
              position={[-0.3, -1.307, 19.923]}
              rotation={[-Math.PI / 2, 0, 0]}
              // material-color={"blue"}
              metalness={0.6}
            />
            {/* <MeshRefractionMaterial color={"blue"} side={THREE.DoubleSide} envMap={env} aberrationStrength={0.02} toneMapped={false} /> */}
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Traditional.gltf");
export default Traditional_ring;
